name: Build and Update Manifests
on:
  repository_dispatch:
    types: [ build-video-api ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4
        with:
          repository: sornharith/app-code
          path: app-code
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Docker Image
        run: |
          cd app-code/app-src
          docker build -t sornharith/app-test:${{ github.run_id }} .
          docker push sornharith/app-test:${{ github.run_id }}
          
      - name: Checkout Infrastructure Code
        uses: actions/checkout@v4
        with:
          path: infra-code
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Update Kubernetes YAML
        run: |
          cd infra-code/infra-yaml
          sed -i "s|image: sornharith/app-test:.*|image: sornharith/app-test:${{ github.run_id }}|g" deployment.yaml
          
          git config user.name "CI Bot"
          git config user.email "bot@example.com"
          git add deployment.yaml
          git commit -m "Auto-deploy version ${{ github.run_id }}"
          git push